import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { BsStack } from "react-icons/bs";
import { FcServices } from "react-icons/fc";
import { GrCircleInformation } from "react-icons/gr";
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Ofis Teknik Kırtasiye</h1>
        <p className={styles.description}>
          100. Yıl Bulvarı Bosna İş Merkezi 35/47 Ostim/ANKARA
        </p>
        <p className={styles.description}>
          Telefon: 0312 385 38 83 354 62 89 Fax:0312 385 30 62
        </p>
        <p className={styles.description}>
          ofisteknikmdk@hotmail.com / info@ofisteknikkirtasiye.com
        </p>
        <p className={styles.description}>
          WhatsApp Sipariş Hattı: 0546 739 94 49
        </p>
      </main>
      <div className={styles.contentmain}>
        <div className={styles.maintext}>
          <BsStack size={48} />
          <h1>
            Ofis Teknik Kırtasiye olarak sizlere %100 müşteri memnuniyetini
            garanti ediyoruz.
          </h1>
        </div>
        <div className={styles.icon}>
          <GrCircleInformation size={48} />
        </div>
        <div className={styles.grid}>
          <div className={styles.informationheadertext}>Biz Kimiz?</div>
          <div className={styles.informationtext}>
            Ofis Teknik MDK Kırtasiye olarak Ankara Ostim 100.Yıl Bulvarı’nda
            siz değerli müşterilerimize hizmet veren bir kırtasiye firmasıyız.
            Siz değerli müşterilerimize uzun yıllardır Kırtasiye malzemesi ve
            bilimum sektörsel alanlarda hizmet vermekteyiz. Önceliğimiz müşteri
            memnuniyetidir. Güleryüzlü ve kaliteli hizmetimizden hiçbir zaman
            ödün vermedik.
          </div>
        </div>
      </div>
      <div className={styles.features}>
        <div className={styles.featurestext}>Hizmet Verdiğimiz Alanlar</div>
        <div className={styles.feature}>
          <div className={styles.featurescard}>
            <h5>Ofis Gereçleri</h5>
          </div>
          <div className={styles.featurescard}>
            <h5>Kaşe</h5>
          </div>
          <div className={styles.featurescard}>
            <h5>Kopyalama</h5>
          </div>
          <div className={styles.featurescard}>
            <h5>Ambalaj</h5>
          </div>
          <div className={styles.featurescard}>
            <h5>Cilt Yapımı</h5>
          </div>
          <div className={styles.featurescard}>
            <h5>Taşıma Kolileri</h5>
          </div>
          <div className={styles.featurescard}>
            <h5>Reklam ve Grafik Hizmetleri</h5>
          </div>
          <div className={styles.featurescard}>
            <h5>İş Makinesi Kiralama</h5>
          </div>
        </div>
      </div>
    </div>
  );
}
